version: "3.8"

services:
  server:
    container_name: server
    build:
      context: ./server
    restart: always
    ports:
      - 5000:5000
    expose:
      - 5000
    depends_on:
      - mongodb

  web:
    container_name: web
    build:
      context: ./client
    restart: always
    ports:
      - 3000:3000
    expose:
      - 3000
    depends_on:
      - server

  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
